// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Identifies crop diseases from an image and suggests solutions in the user's language.
 *
 * - analyzeCrop - Analyzes a crop image for diseases and suggests solutions.
 * - AnalyzeCropInput - The input type for the analyzeCrop function.
 * - AnalyzeCropOutput - The return type for the analyzeCrop function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeCropInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      'A photo of the crop, as a data URI that must include a MIME type and use Base64 encoding. Expected format: data:<mimetype>;base64,<encoded_data>.'
    ),
  language: z
    .string()
    .describe('The language in which the solution should be provided.'),
});
export type AnalyzeCropInput = z.infer<typeof AnalyzeCropInputSchema>;

const AnalyzeCropOutputSchema = z.object({
  disease: z.string().describe('The identified disease of the crop.'),
  solution: z.string().describe('The suggested solution for the disease.'),
});
export type AnalyzeCropOutput = z.infer<typeof AnalyzeCropOutputSchema>;

export async function analyzeCrop(input: AnalyzeCropInput): Promise<AnalyzeCropOutput> {
  return analyzeCropFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzeCropPrompt',
  input: {schema: AnalyzeCropInputSchema},
  output: {schema: AnalyzeCropOutputSchema},
  prompt: `You are an expert in identifying crop diseases and suggesting solutions.

  Analyze the following crop image and identify any potential diseases. Provide a solution in the specified language.

  Language: {{{language}}}
  Photo: {{media url=photoDataUri}}
  `,
  model: 'gemini-1.5-flash',
});

const analyzeCropFlow = ai.defineFlow(
  {
    name: 'analyzeCropFlow',
    inputSchema: AnalyzeCropInputSchema,
    outputSchema: AnalyzeCropOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
